version: '3'

services:

  nginx:
    image: thiagootoni/fc-nginx:desafio2
    container_name: nginx
    networks: 
      - node-network
    ports:
      - 8080:8080
    depends_on:
       - db

  app:
    image: thiagootoni/fc-node:desafio2
    container_name: app
    networks: 
      - node-network
    volumes: 
      - ./Node:/usr/src/app
    tty: true
    expose:
      - "3000"
    depends_on:
       - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    expose:
      - "3606"
    volumes: 
      - ./Mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network

networks: 
  node-network:
    driver: bridge      