version: '3'

services:

  nginx:
    build:
      context: Nginx
    container_name: nginx
    networks: 
      - node-network
    ports:
      - 8080:8080
    depends_on:
       - db

  app:
    build:
      context: Node
    container_name: app
    networks: 
      - node-network
    volumes: 
      - ./Node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    expose:
      - "3000"
    depends_on:
       - db

  db:
    build:
      context: Mysql
    container_name: db
    restart: always
    tty: true
    expose:
      - "3606"
    volumes: 
      - ./Mysql/shared_volume:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network

networks: 
  node-network:
    driver: bridge      